### ISSUE TITLE
Orphan artifact : change the artifactId create a new artifact without delete the old. 

### ISSUE THREAD

**Issue by mpusg** [Apicurio/apicurio-registry-content-sync-operator#111]
Hi All, 

I detected a new issue on the apicurio's operator inside openshift. 
Inside a CRD of an apicurio artifact, when I change the value of the artifactId field, the operator create a new artifact inside apicurio registry. This behavior of creation is correct. But the old artefact has not been deleted, and It is no longer managed by the operator. The old artefact become an orphan.

So I have a CRD named kafka-sample-kafka-sample-pet-mpusg-1 which contain its spec like this : 

```yaml
spec:
  modifiedBy: ''
  modifiedOn: '2022-09-23T13:08:36+0000'
  name: kafka-sample-kafka-sample-pet-mpusg
  artifactId: com.company.mpusg.test.Pet
  state: ENABLED
  properties: {}
  contentId: 66
  version: '1'
  content: >-
    {"type":"record","name":"Pet","namespace":"com.company.mpusg.test","fields":[{"name":"name","type":"string"},{"name":"age","type":["int","null"]}]}
  type: AVRO
  description: MPUSG pet test
  globalId: 205
  labels:
    - avro
    - kafka
status:
  artifactId: com.company.mpusg.test.Pet
  globalId: 205
  status: ready
  version: '1'
```
I see it by registry/v2 rest api : 

```bash
curl https://myregistry.company.com/apis/registry/v2/groups/default/artifacts | jq '.artifacts[].id'
"com.company.mpusg.test.Pet" 
```

I change only the value of the artifactId field. 

```yaml
spec:
  modifiedBy: ''
  modifiedOn: '2022-09-23T13:48:17+0000'
  name: kafka-sample-kafka-sample-pet-mpusg
  artifactId: com.company.mpusg.test.Pet.new
  state: ENABLED
  properties: {}
  contentId: 66
  version: '1'
  content: >-
    {"type":"record","name":"Pet","namespace":"com.company.mpusg.test","fields":[{"name":"name","type":"string"},{"name":"age","type":["int","null"]}]}
  type: AVRO
  description: MPUSG pet test
  globalId: 206
  labels:
    - avro
    - kafka
status:
  artifactId: com.company.mpusg.test.Pet.new
  globalId: 206
  status: ready
  version: '1'
```  
  
curl https://myregistry.company.com/apis/registry/v2/groups/default/artifacts | jq '.artifacts[].id'
"com.company.mpusg.test.Pet" 
"com.company.mpusg.test.Pet.new" 

A new artifact is created with the name "com.company.mpusg.test.Pet.new" but the old is always up. When I push a new schema, the new version is applicate only on "com.company.mpusg.test.Pet.new". From the change on the artifactId, the operator loses control over the old one.

Can you analyze ? Thanks for your investigations.
