### ISSUE TITLE
Define content rules over CRD

### ISSUE THREAD

**Issue by dweber019** [Apicurio/apicurio-registry-content-sync-operator#23]
It would be nice to define the content rules described on https://www.apicur.io/registry/docs/apicurio-registry/2.1.x/getting-started/assembly-intro-to-registry-rules.html in https://github.com/Apicurio/apicurio-registry-content-sync-operator/blob/main/api/src/main/java/io/apicurio/sync/api/ArtifactSpec.java.

Use case: We have AVRO definitions which have different compatibility configurations.

**Comment by famartinrh** [comment]
great suggestion, this is a natural step.

Apicurio Registry supports configuring rules that apply globally to all artifacts and rules specific to one artifact (so that rule will be applied to all artifact versions)

**Comment by dweber019** [comment]
@famartinrh I can do a PR. Would implement the rules in the same CRD but as optional fields.
Ok?

**Comment by famartinrh** [comment]
@dweber019 I think this makes more sense to be implemented into a separated CRD. Rules are an entity of it's own in Apicurio Registry.

Something like
```
apiVersion: rule.apicur.io/v1alpha1
kind: Rule
metadata:
  name: validity-global
spec:
  type: VALIDITY
  config: SYNTAXT_ONLY
```
and
```
apiVersion: rule.apicur.io/v1alpha1
kind: Rule
metadata:
  name: compat-artifact-foo
spec:
  type: COMPATIBILITY
  config: BACKWARD
  groupId: test-group
  artifactId: foo
```
